name: Deploy Docker Image

runs-on: ubuntu-latest
needs: [build, scan]

steps:
  - name: Log in to Docker Hub
    uses: docker/login-action@v3
    with:
      username: ${{ env.DOCKER_USERNAME }}      
      password: ${{ secrets.DOCKER_PASSWORD }}
      
  - name: Push Docker images
    run: |
      docker push ${{ env.DOCKER_USERNAME }}/android:${{ needs.build.outputs.image_version }}
      docker push ${{ env.DOCKER_USERNAME }}/android:latest

  - name: Clean up Docker images
    run: |
      docker image prune -af
