name: Docker Image Health Check

on:
  pull_request:
    branches:
      - master

jobs:
  docker-build-run:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: "mahmoudazaid"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for linux/amd64 and linux/arm64/v8
        run: |
          echo "Building Docker image for linux/amd64 and linux/arm64/v8"
          docker buildx build \
            --platform linux/amd64,linux/arm64/v8 \
            -t android-image:${{ github.sha }} \
            --load .

      - name: Check if the Docker image runs for linux/amd64
        run: |
          echo "Running container for linux/amd64"
          docker run -d -e APPIUM=true --name test-android-image-amd64 --platform linux/amd64 android-image:${{ github.sha }}

          echo "Waiting for the container to start..."
          sleep 10  

          if [[ $(docker ps -q -f name=test-android-image-amd64) ]]; then
              echo "Container for linux/amd64 is up and running."
          else
              echo "Container for linux/amd64 failed to start."
              exit 1
          fi

          docker logs test-android-image-amd64

      - name: Check if the Docker image runs for linux/arm64
        run: |
          echo "Running container for linux/arm64"
          docker run -d -e APPIUM=true --name test-android-image-arm64 --platform linux/arm64/v8 android-image:${{ github.sha }}

          echo "Waiting for the container to start..."
          sleep 10  

          if [[ $(docker ps -q -f name=test-android-image-arm64) ]]; then
              echo "Container for linux/arm64 is up and running."
          else
              echo "Container for linux/arm64 failed to start."
              exit 1
          fi

          docker logs test-android-image-arm64

      - name: Clean up
        run: |
          docker stop test-android-image-amd64
          docker rm test-android-image-amd64
          docker stop test-android-image-arm64
          docker rm test-android-image-arm64
