name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag for the Docker image'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: "mahmoudazaid"
      BASE_IMAGE: "mahmoudazaid/android-build-tools:35.0.0"  # Define the base image to check and use
      VERSION: ${{ github.event.inputs.version || 'latest' }}  # Default to 'latest' version if not provided

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: ~/.cache/docker
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Check if base image needs update
      run: |
        # Pull the base image to check for updates
        docker pull ${BASE_IMAGE}
        echo "Base image ${BASE_IMAGE} pulled successfully."

    - name: Extract version from Dockerfile
      id: extract_version
      run: |
        # Extract the version from the Dockerfile if it's set there
        VERSION=$(grep -m 1 'LABEL version' Dockerfile | cut -d '=' -f2 | tr -d '"')
        if [ -z "$VERSION" ]; then
          VERSION=$(grep -m 1 'ENV VERSION' Dockerfile | cut -d '=' -f2 | tr -d '"')
        fi
        echo "VERSION=$VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        # Build and tag the Docker image
        docker build -t ${{ env.DOCKER_USERNAME }}/android:${{ env.VERSION }} .
        docker build -t ${{ env.DOCKER_USERNAME }}/android:latest .

    - name: Push Docker image
      run: |
        # Push the Docker images to Docker Hub
        docker push ${{ env.DOCKER_USERNAME }}/android:${{ env.VERSION }}
        docker push ${{ env.DOCKER_USERNAME }}/android:latest

    - name: Clean up Docker images
      run: |
        # Clean up dangling Docker images
        docker image prune -af
