name: Docker Publish

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag for the Docker image'
        default: 'latest'
  repository_dispatch:
    types: [docker-image-updated]

env:
  DOCKER_USERNAME: "mahmoudazaid"

jobs:
  PUBLISH_DOCKER_IMAGE:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: ~/.cache/docker
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version from Dockerfile if not provided
        id: extract_version
        run: |
          VERSION=$(grep -m 1 -E '^(LABEL|ENV|ARG)\s+ANDROID_VERSION=' Dockerfile | cut -d '=' -f2 | tr -d '"')
          echo "VERSION=$VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      
      - name: Fail if no version is set
        if: env.VERSION == ''
        run: |
          echo "Error: ANDROID_VERSION is missing in the Dockerfile."
          exit 1

      - name: Build and Push Platform linux/amd64 Docker Image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t ${{ env.DOCKER_USERNAME }}/android:${{ env.VERSION }} \
            -t ${{ env.DOCKER_USERNAME }}/android:latest \
            --push .

      - name: Clean up Docker images
        run: |
          docker image prune -af
