name: Check Docker Image Check

on:
  pull_request:
    branches:
      - master 

jobs:
  docker-build-run:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: "mahmoudazaid"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t android-image:${{ github.sha }} .  

    - name: Check if the Docker image runs
      run: |
        docker run -d -e APPIUM=true --name test-android-image android-image:${{ github.sha }}
        sleep 10  
        docker ps -a
        docker logs test-android-image

    - name: Clean up
      run: |
        docker stop test-android-image
        docker rm test-android-image