name: Docker Image Health Check

on:
  pull_request:
    branches:
      - master

jobs:
  docker-build-run:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: "mahmoudazaid"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        install: true

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image for linux/amd64
      run: |
        docker buildx build \
          --platform linux/amd64 \
          -t ${{ env.DOCKER_USERNAME }}/android-image:${{ github.sha }} \
          -t ${{ env.DOCKER_USERNAME }}/android-image:latest \
          --load .

    - name: Test Docker Image on linux/amd64
      run: |
        echo "Testing Docker image on linux/amd64"
        docker run --platform linux/amd64 -d -p "4723:4723" --device /dev/kvm --name test-android-image-amd64 ${{ env.DOCKER_USERNAME }}/android-image:${{ github.sha }}
        sleep 60  # Wait to ensure Appium and emulator have time to start.

        # Check if Appium server started successfully
        echo "Checking Appium server status"
        status_output=$(docker exec test-android-image-amd64 curl -s http://localhost:4723/status || echo "fail")
        if echo "$status_output" | grep -q '"ready":true'; then
          echo "Appium server is running."
        else
          echo "Appium server did not start successfully. Response: $status_output"
          docker logs test-android-image-amd64
          docker stop test-android-image-amd64 || true
          docker rm test-android-image-amd64 || true
          exit 1
        fi

        # Check if the emulator is running
        echo "Checking Android emulator status..."
        devices=$(docker exec test-android-image-amd64 adb devices || echo "fail")
        echo "Devices found: $devices"
        if ! echo "$devices" | grep -q "emulator"; then
          echo "Error: No Android emulator is running."
          docker logs test-android-image-amd64
          docker stop test-android-image-amd64 || true
          docker rm test-android-image-amd64 || true
          exit 1
        fi
        echo "Android emulator is running."

    - name: Clean up
      run: |
        docker stop test-android-image-amd64 || true
        docker rm test-android-image-amd64 || true