name: Scan Docker Image

runs-on: ubuntu-latest
needs: build

steps:
  - name: Log in to Docker Hub
    uses: docker/login-action@v3
    with:
      username: ${{ env.DOCKER_USERNAME }}
      password: ${{ env.DOCKER_PASSWORD }}

  - name: Install Docker Scout
    run: |
      curl -fsSL ${{ env.DOCKER_SCOUT_URL }} | tar xz -C /usr/local/bin
      sudo chmod +x /usr/local/bin/docker-scout
      docker-scout version

  - name: Run Docker Scout to scan the images
    run: |
      docker-scout cves ${{ needs.build.outputs.image_version }}
      docker-scout cves ${{ needs.build.outputs.image_version }}:latest
